/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
// -----------------------------------------------------------------------------
L_ambiDrive_fnc_civManager				= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\civManager.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_deleteCheck				= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\deleteCheck.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_findRoad 				= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\findRoad.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_getPlayers				= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\getPlayers.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_getElevationMultiplicatorValue = compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\getElevationMultiplicatorValue.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_getRandomPos			= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\getRandomPos.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_getRoadDir				= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\getRoadDir.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_posCache				= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\posCache.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_positionSuitable		= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\positionSuitable.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_spawnCar				= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\spawnCar.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_spawnCiv				= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\spawnCiv.sqf";

// -----------------------------------------------------------------------------
L_ambiDrive_fnc_spawnManager			= compile preprocessFileLineNumbers "scripts\L_ambiDrive\fncs\spawnManager.sqf";
/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/







