// Unit classes that will be spawned
L_ambiCivs_civClasses  = [
	"UK3CB_ADC_C_CIV_CHR_01",
	"UK3CB_ADC_C_CIV_CHR_02",
	"UK3CB_ADC_C_CIV_ISL_01",
	"UK3CB_ADC_C_HUNTER_CHR",
	"UK3CB_ADC_C_CIT",
	"UK3CB_ADC_C_COACH",
	"UK3CB_ADC_C_PROF",
	"UK3CB_ADC_C_VILL",
	"UK3CB_ADC_C_WOOD",
	"UK3CB_ADC_C_FUNC",
	"UK3CB_ADC_C_LABOURER_CHR",
	"UK3CB_ADC_C_LABOURER_ISL",
	"UK3CB_ADC_C_CIV_CHR",
	"UK3CB_ADC_C_CIV_ISL",
	"UK3CB_ADC_C_SPOT_CHR",
	"UK3CB_ADC_C_SPOT_ISL",
	"UK3CB_ADC_C_WORKER"
];

