/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/
// -----------------------------------------------------------------------------
L_ambiCivs_fnc_civManager				= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\civManager.sqf";

// -----------------------------------------------------------------------------
L_ambiCivs_fnc_spawnManager				= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\spawnManager.sqf";

// -----------------------------------------------------------------------------
L_ambiCivs_fnc_positionSuitable			= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\positionSuitable.sqf";

// -----------------------------------------------------------------------------
L_ambiCivs_fnc_spawnCiv					= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\spawnCiv.sqf";

// -----------------------------------------------------------------------------
L_ambiCivs_fnc_deleteCheck				= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\deleteCheck.sqf";

// -----------------------------------------------------------------------------
L_ambiCivs_fnc_getPlayers				= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\getPlayers.sqf";

// -----------------------------------------------------------------------------
L_ambiCivs_fnc_getRandomPos				= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\getRandomPos.sqf";

// -----------------------------------------------------------------------------
L_ambiCivs_fnc_getRoadAdditionFactor	= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\getRoadAdditionFactor.sqf";

// -----------------------------------------------------------------------------
L_ambiCivs_fnc_getElevationMultiplicatorValue	= compile preprocessFileLineNumbers "scripts\L_ambiCivs\fncs\getElevationMultiplicatorValue.sqf";

/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!    !! DO NOT EDIT THIS FILE !!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!    !!!!!!!!!!!!!!!!!!!!!!!!!!!
*/







